[package]
name = "sucuri_lcs"
version = "0.1.0"
edition = "2021"

[lib]
name = "sucuri_lcs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py38"] }
